name: vcf-annotate-snpeff-snpsift
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::python=3.7.3
  - conda-forge::pytest=5.3.0
  - conda-forge::datrie=0.8
  - conda-forge::git=2.23.0
  - conda-forge::jinja2=2.10.3
  - conda-forge::pygraphviz=1.5
  - conda-forge::flask=1.1.1
  - conda-forge::pandas=0.25.3
  - conda-forge::zlib=1.2.11
  - conda-forge::openssl=1.1.1d
  - conda-forge::networkx=2.4
  - bioconda::snakemake=5.8.1
